- name: Tampilkan collection yang tersedia
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Lihat collection yang terinstall
      shell: ansible-galaxy collection list
      register: hasil

    - name: Tampilkan hasil
      debug:
        var: hasil.stdout_lines
