---
- name: Get current username on localhost
  hosts: localhost
  gather_facts: false # No need to gather facts for this simple task

  tasks:
    - name: Execute 'whoami' command
      ansible.builtin.command: whoami
      register: user_info # Store the output in 'user_info' variable

    - name: Display the username
      ansible.builtin.debug:
        msg: "The AWX task on {{ inventory_hostname }} is running as user: {{ user_info.stdout | trim }}"
