---
- name: Check current user on localhost
  hosts: localhost # Menargetkan hanya localhost
  gather_facts: false # Tidak perlu mengumpulkan fakta, mempercepat eksekusi

  tasks:
    - name: Get the effective user
      ansible.builtin.command: whoami
      register: current_user_info # Menyimpan output perintah ke variabel ini

    - name: Display the current user
      ansible.builtin.debug:
        msg: "The AWX task is being executed by user: {{ current_user_info.stdout }}"
