- name: Tes koneksi dengan Ansible module
  hosts: localhost
  gather_facts: false
  collections:
    - community.mysql
  tasks:
    - name: Cek koneksi MySQL
      mysql_query:
        login_host: 192.168.67.1
        login_user: awx
        login_password: awx123
        query: "SHOW DATABASES;"
      register: hasil_query

    - name: Tampilkan hasil query
      debug:
        var: hasil_query
